### ISSUE TITLE
Transferred content has quotation-marks and apostrophes removed. 

### ISSUE THREAD

**Issue by Bergene** [paperboi/kindle2notion#43]
Hi.

I just updated kindle2notion from 0.1.2 to 0.1.7.

I took a backup of all my Clippings in Notion, deleted the original pages and transferred the content from 'My Clippings.txt' to a fresh Notion database.

Now all quotation-marks and apostrophes are missing when displayed in Notion. Now all the lines just kind of blend in with another, I am not able to separate what is thought, description or quotes. 

The quotation-marks and apostrophes are still present in 'My Clippings.txt' and even in my backup Clippings Notion Database (used kindle2notion 0.1.2, so I know that this was working before).

**Comment by paperboi** [comment]
That's odd, hadn't noticed that before. My Clippings file doesn't contain quotation marks between each clipping. Will add em manually for each highlight and ignore for notes in the next commit.

**Comment by Bergene** [comment]
It was a new issue for me when updating to 0.1.7, previously I have not experienced this. 

The comment/note/highlights should look like this:
`“I’m no highspren,” the captain spat. “I can see that the variety of humankind is what gives you strength. Your ability to change your minds, to go against what you once thought, can be a great advantage. But your bond is dangerous, without Honor. There will not be enough checks upon your power—you risk disaster.”`

But when the transfer to Notion is complete the same comment/note/highlight looks like this: 
`Im no highspren, the captain spat. I can see that the variety of humankind is what gives you strength. Your ability to change your minds, to go against what you once thought, can be a great advantage. But your bond is dangerous, without Honor. There will not be enough checks upon your poweryou risk disaster.`

This can be an issue when trying to decipher if it's a quote from a person or just commentary.

**Comment by Bergene** [comment]
For now I have reverted back to version 0.1.2 as the quotes and apostrophes are untouched in this version.

**Comment by paperboi** [comment]
Hi @Bergene! This issue is addressed in the latest release aka kindle2notion 0.1.8.
Thank you for your patience and hope this clears this particular problem up.

**Comment by Bergene** [comment]
Thank you. I will test ut asap.

**Comment by Bergene** [comment]
Hi @paperboi.
The issue is unfortunately not fixed in 0.1.8. I just tested it and all the quotation marks and apostrophes are removed from the transferred text. 

I love the additions of highlighting the notes and such though in the new version.

**Comment by abishekmuthian** [comment]
I confirm this issue persists in 0.1.8, Will investigate further during the weekend.

**Comment by paperboi** [comment]
Hi, fixed this in the latest release, please update :)
